/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#1e2628",
        "inverse-primary": "#006b5d",
        "inverse-on-surface": "#2c3132",
        "tertiary-container": "#28efd6",
        "surface-bright": "#1f292b",
        "outline-variant": "#223334",
        "tertiary-fixed-dim": "#00dfc6",
        "on-tertiary-fixed": "#00201b",
        "primary-fixed-dim": "#00dfc5",
        "primary": "#bffff0",
        "on-secondary-fixed": "#002021",
        "on-primary-fixed-variant": "#005046",
        "on-surface": "#e6edf0",
        "secondary": "#42e0e5",
        "on-tertiary": "#003730",
        "surface-container-low": "#0b1113",
        "on-primary-fixed": "#00201b",
        "secondary-fixed": "#61f7fc",
        "on-tertiary-fixed-variant": "#005047",
        "tertiary": "#befff1",
        "surface-tint": "#00dfc5",
        "on-secondary-fixed-variant": "#004f51",
        "on-secondary": "#003738",
        "error": "#ffb4ab",
        "on-primary": "#003730",
        "surface": "#070a0b",
        "tertiary-fixed": "#41fce2",
        "surface-dim": "#050708",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-container-lowest": "#040607",
        "surface-container-high": "#162022",
        "background": "#070a0b",
        "on-secondary-container": "#004c4e",
        "secondary-container": "#00c4c9",
        "inverse-surface": "#dfe3e4",
        "surface-container-highest": "#202c2e",
        "on-background": "#dfe3e4",
        "surface-container": "#0e1517",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#9cb2ad",
        "primary-container": "#00f0d4",
        "on-tertiary-container": "#00685c",
        "outline": "#627d78",
        "secondary-fixed-dim": "#39dbe0",
        "on-primary-container": "#003b34",
        "primary-fixed": "#30fde1"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.375rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
